### ISSUE TITLE
open the .rec file error

### ISSUE THREAD

**Issue by guslijif** [chalmers-revere/opendlv-video-h264-replay#1]
I was trying to decode h264 video frames from a given .rec file into a shared memory, I have successfully implemented the opendlv-video-h264-replay image in my docker.
The problem is when I try  `docker run --rm -ti --net=host --ipc=host -v /tmp:/tmp video-replay:latest --cid=253 --name=img 150001.rec`
the terminal return `/usr/bin/opendlv-video-h264-replay: Failed to open '150001.rec'`
I thought it might be the problem with directory, so I try  `docker run --rm -ti --net=host --ipc=host -v $PWD:/tmp video-replay:latest --cid=253 --name=img 145043.rec` 
the terminal still return  `/usr/bin/opendlv-video-h264-replay: Failed to open '150001.rec'`

I am not sure if I lack some dependence or may be miss input the parameter.

**Comment by chrberger** [comment]
Hi, the Docker container cannot find the recording file.

docker run --rm -ti --net=host --ipc=host -v /tmp:/tmp -v $PWD:/host -w /host video-replay:latest --cid=253 --name=img 150001.rec

should do it as long as 150001.rec is present in $PWD.
